version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cp api/.env.example api/.env

      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Start container api and verify it's working
          command: |
            set -x
            cd api
            docker-compose build
  test:
    machine: true
    steps:
      - run: cd api
      - run: docker-compose up -d
      - run: curl http://localhost:3232/vws/api/v1/fiatrates/eur
  deploy-db:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a9:8f:77:d2:f2:e2:3d:ef:62:4f:08:49:c2:6f:96:f3"
      - run: scp ./db/nginx.conf $VWS1:/home/vegadmin/test
  deploy-api:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ae:76:6a:4e:cf:73:48:39:ab:5f:d5:31:96:8b:50:f5"
      - run: scp ./api/nginx.conf $VWS1:/home/vegadmin/test
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test
      - deploy-db:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - deploy-api:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
