version: 2
jobs:
  deploy-db:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "a9:8f:77:d2:f2:e2:3d:ef:62:4f:08:49:c2:6f:96:f3"

      - run:
          name: Copy DB files
          command: |
            scp ./install.sh $XVGDB01:/home/$REMOTE_USER
            scp ./db/docker-compose.yml $XVGDB01:/home/$REMOTE_USER
            scp ./db/nginx.conf $XVGDB01:/home/$REMOTE_USER
            scp ./db/nginx/whitelist.conf $XVGDB01:/home/$REMOTE_USER/nginx
            scp ./db/nginx/html/index.html $XVGDB01:/home/$REMOTE_USER/nginx/html

      - run:
          name: Start docker-compose
          command: |
            ssh $XVGDB01 'cd ~ && sh install.sh'
            ssh $XVGDB01 'cd ~ && docker-compose pull'
            ssh $XVGDB01 'cd ~ && docker-compose down'
            ssh $XVGDB01 'cd ~ && docker-compose up -d'

  deploy-api:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ae:76:6a:4e:cf:73:48:39:ab:5f:d5:31:96:8b:50:f5"

      - run:
          name: Copy API files
          command: |
            scp ./install.sh $XVGAPI01:/home/$REMOTE_USER
            scp ./api/docker-compose.yml $XVGAPI01:/home/$REMOTE_USER
            scp ./api/nginx.conf $XVGAPI01:/home/$REMOTE_USER
            scp ./api/nginx/html/index.html $XVGAPI01:/home/$REMOTE_USER/nginx/html
            scp ./api/bitcore.config.json $XVGAPI01:/home/$REMOTE_USER

      - run:
          name: Start docker-compose
          command: |
            ssh $XVGAPI01 'cd ~ && sh install.sh'
            ssh $XVGAPI01 'cd ~ && docker-compose pull'
            ssh $XVGAPI01 'cd ~ && docker-compose down'
            ssh $XVGAPI01 'cd ~ && docker-compose up -d'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy-db:
          filters:
            branches:
              only: master
      - deploy-api:
          requires:
            - deploy-db

