version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bitcore-node
      - bitcore-wallet-service
      - verge-price-ticker
    restart: always

  verged:
    image: hdsign/verge-core:latest
    ports:
      - "21102:21102"
      - "20102:20102"
    volumes:
      - ./VERGE/:/root/.VERGE
    restart: always

  bitcore-node:
    image: hdsign/bitcore:latest
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=${BN_MONGODB_HOST}
      - DB_NAME=${BN_MONGODB_NAME}
      - DB_PORT=${BN_MONGODB_PORT}
    depends_on:
      - verged
    volumes:
      - ./bitcore.config.json:/usr/src/app/bitcore.config.json
    restart: always
    command: npm run node
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/XVG/mainnet/block/tip"]
      interval: 1m
      timeout: 10s
      retries: 2

  bitcore-wallet-service:
    image: hdsign/bitcore:latest
    links:
      - bitcore-node
    ports:
      - "3232:3232"
      - "3380:3380"
    environment:
      - BWS_MONGODB_URL=${BWS_MONGODB_URL}
      - BWS_NODE_URL=${BWS_NODE_URL}
    depends_on:
      - bitcore-node
    volumes:
      - ./logs/vws/:/usr/src/app/packages/bitcore-wallet-service/logs
    restart: always
    command: /usr/src/app/packages/bitcore-wallet-service/docker-cmd.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3232/vws/api/v1/fiatrates/eur"]
      interval: 1m
      timeout: 10s
      retries: 1

  verge-price-ticker:
    image: hdsign/verge-price-ticker:latest
    ports:
      - "3003:3003"
    environment:
      - VPT_MONGODB_URL=${VPT_MONGODB_URL}
    restart: always
    command: npm run prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/api/v1/price/usd"]
      interval: 1m
      timeout: 10s
      retries: 1

  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
